server:
  port: 7777
spring:
  devtools:
    livereload:
      enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/non_jpa_db?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: khweb
    password: khWeb@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true