server:
  port: 7777
spring:
  devtools:
    livereload:
      enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/non_jpa_db?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: khweb
    password: khWeb@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  h2:
    console:
      enabled: true

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true